namespace Ditch.Golos.Operations
{
    /// <summary>
    /// https://github.com/steemit/steem/blob/master/libraries/protocol/include/steemit/protocol/operations.hpp
    ///  NOTE= do not change the order of any operations
    /// </summary>
    public enum OperationType : byte
    {
        // _16 for 0.16.4
        Vote16 = 0,
        Comment16 = 1,
        Transfer16 = 2,
        TransferToVesting16 = 3,
        WithdrawVesting16 = 4,
        LimitOrderCreate16 = 5,
        LimitOrderCancel16 = 6,
        FeedPublish16 = 7,
        Convert16 = 8,
        AccountCreate16 = 9,
        AccountUpdate16 = 10,
        WitnessUpdate16 = 11,
        AccountWitnessVote16 = 12,
        AccountWitnessProxy16 = 13,
        Pow16 = 14,
        //
        Custom = 15,
        //
        ReportOverProduction16 = 16,
        DeleteComment16 = 17,
        //
        CustomJson = 18,
        //
        CommentOptions16 = 19,
        SetWithdrawVestingRoute16 = 20,
        LimitOrderCreate216 = 21,
        ChallengeAuthority16 = 22,
        ProveAuthority16 = 23,
        RequestAccountRecovery16 = 24,
        RecoverAccount16 = 25,
        ChangeRecoveryAccount16 = 26,
        EscrowTransfer16 = 27,
        EscrowDispute16 = 28,
        EscrowRelease16 = 29,
        Pow216 = 30,
        EscrowApprove16 = 31,
        TransferToSavings16 = 32,
        TransferFromSavings16 = 33,
        CancelTransferFromSavings16 = 34,
        //
        CustomBinary = 35,
        //
        DeclineVotingRights16 = 36,
        ResetAccount16 = 37,
        SetResetAccount16 = 38,
        CommentBenefactorReward16 = 39,
        //
        Vote = 40,
        Comment = 41,
        Transfer = 42,
        TransferToVesting = 43,
        WithdrawVesting = 44,
        LimitOrderCreate = 45,
        LimitOrderCancel = 46,
        FeedPublish = 47,
        Convert = 48,
        AccountCreate = 49,
        AccountUpdate = 50,
        WitnessUpdate = 51,
        AccountWitnessVote = 52,
        AccountWitnessProxy = 53,
        Pow = 54,
        ReportOverProduction = 55,
        DeleteComment = 56,
        CommentOptions = 57,
        SetWithdrawVestingRoute = 58,
        LimitOrderCreate2 = 59,
        ChallengeAuthority = 60,
        ProveAuthority = 61,
        RequestAccountRecovery = 62,
        RecoverAccount = 63,
        ChangeRecoveryAccount = 64,
        EscrowTransfer = 65,
        EscrowDispute = 66,
        EscrowRelease = 67,
        Pow2 = 68,
        EscrowApprove = 69,
        TransferToSavings = 70,
        TransferFromSavings = 71,
        CancelTransferFromSavings = 72,
        DeclineVotingRights = 73,
        ResetAccount = 74,
        SetResetAccount = 75,
        CommentBenefactorReward = 76,
        DelegateVestingShares = 77,
        AccountCreateWithDelegation = 78,
        CommentPayoutExtension = 79,
        AssetCreate = 80,
        AssetUpdate = 81,
        AssetUpdateBitasset = 82,
        AssetUpdateFeedProducers = 83,
        AssetIssue = 84,
        AssetReserve = 85,
        AssetFundFeePool = 86,
        AssetSettle = 87,
        AssetForceSettle = 88,
        AssetGlobalSettle = 89,
        AssetPublishFeed = 90,
        AssetClaimFees = 91,
        CallOrderUpdate = 92,
        AccountWhitelist = 93,
        OverrideTransfer = 94,
        ProposalCreate = 95,
        ProposalUpdate = 96,
        ProposalDelete = 97,
        BidCollateral = 98,
        // _16 for 0.16.4
        FillConvertRequest16 = 99,
        AuthorReward16 = 100,
        CurationReward16 = 101,
        CommentReward16 = 102,
        LiquidityReward16 = 103,
        Interest16 = 104,
        FillVestingWithdraw16 = 105,
        FillOrder16 = 106,
        ShutdownWitness16 = 107,
        FillTransferFromSavings16 = 108,
        Hardfork16 = 109,
        CommentPayoutUpdate16 = 110,
        //
        FillConvertRequest = 111,
        AuthorReward = 112,
        CurationReward = 113,
        CommentReward = 114,
        LiquidityReward = 115,
        Interest = 116,
        FillVestingWithdraw = 117,
        FillOrder = 118,
        ShutdownWitness = 119,
        FillTransferFromSavings = 120,
        Hardfork = 121,
        CommentPayoutUpdate = 122,
        ReturnVestingDelegation = 123,
        AssetSettleCancel = 124,
        FillCallOrder = 125,
        FillSettlementOrder = 126,
        ExecuteBid = 127,
    }
}